// ==========================================
// TRANSLATION DATA FILE — Edit once to update both versions
// ==========================================

import { withServiceImages } from "./serviceImages";
import { FALLBACK_LOCALE, type Locale } from "./i18n";

export type ClientLogo = { src: string; alt: string };

export const clientLogos: ClientLogo[] = [
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/pepsi-1.png", alt: "Pepsi" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/rotana.png", alt: "Rotana" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/zayed-1.png", alt: "Zayed" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/mbc.png", alt: "MBC" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/mercdes-1.png", alt: "Mercedes-Benz" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/01/orascom.png", alt: "Orascom" },
  { src: "https://globaluntoldstory.com/wp-content/uploads/2026/02/13-.png", alt: "Client" },
];

export const translations = {
  ar: {
    siteConfig: {
      name: "The Untold Story",
      tagline: "استوديو إنتاج أفلام وفيديو",
      description: "خدمات إنتاج أفلام وفيديو في مصر ومنطقة الشرق الأوسط وشمال أفريقيا — دورة إنتاج كاملة من التخطيط إلى التسليم النهائي.",
      email: "bendary@globaluntoldstory.com",
      phone: "+201001299639",
      address: "Egyptian Media Production City, Egypt",
      workingHours: "الأحد – الخميس، ٩ص – ٦م",
      socialLinks: {
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
        youtube: "https://youtube.com",
      },
    },
    navLinks: [
      { href: "/", label: "الرئيسية" },
      { href: "/about", label: "من نحن" },
      { href: "/services", label: "خدماتنا" },
      { href: "/portfolio", label: "أعمالنا" },
      { href: "/blog", label: "المدونة" },
      { href: "/contact", label: "تواصل معنا" },
    ],
    common: {
      dashboardBtn: "لوحة التحكم",
      readMore: "اقرأ المزيد",
      requestService: "احصل على عرض سعر",
      contactUs: "تواصل معنا",
      contactUsNow: "تواصل معنا الآن",
      exploreServices: "استكشف الخدمات",
      allServices: "جميع الخدمات بالتفصيل",
      successTitle: "تم الإرسال بنجاح!",
      successDesc: "وصلتنا رسالتك وسيتواصل معك فريقنا خلال ٢٤ ساعة.",
      sendAnother: "إرسال رسالة أخرى",
      loading: "⏳ جارٍ الإرسال...",
      submitBtn: "إرسال الرسالة",
      whyUs: "لماذا The Untold Story?",
    },
    heroData: {
      badge: "🎬 إنتاج أفلام وفيديو في مصر ومنطقة الشرق الأوسط وشمال أفريقيا",
      headline1: "The Untold Story",
      headline2: "تقدّم دورة الإنتاج الكاملة",
      subtext: "أفلام، فيديو، إعلانات، أفلام وثائقية، محتوى مؤسسي، برامج تلفزيونية، والمزيد. مكاتبنا في مدينة الإنتاج الإعلامي بمصر ودبي وجدة لخدمة المنطقة والعملاء حول العالم.",
      cta1: { label: "تواصل معنا للمشروع القادم ←", href: "/contact" },
      cta2: { label: "أعمالنا", href: "/portfolio" },
      image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop",
      imageAlt: "إنتاج أفلام وفيديو احترافي",
      badges: ["تخطيط ✓", "تصوير ✓", "ما بعد الإنتاج ✓", "تعريب ✓"],
      quoteBadge: "احصل على عرض سعر خلال 24 ساعة",
    },
    homeData: {
      servicesBadge: "خبرتنا في السرد والإنتاج",
      servicesTitle: "خبرتنا في السرد والإنتاج",
      servicesSubtext: "حلول إنتاج متكاملة للعلامات والمنصات والقنوات والمؤسسات",
      servicesCta: "المزيد من الخدمات لاحتياجاتك. تواصل معنا",
      productionPipeline: ["التخطيط", "التصوير", "البث المباشر", "ما بعد الإنتاج والتسليم", "التعريب"],
      portfolioTitle: "مشاريع من إنجاز The Untold Story",
      quoteBadge: "حيث تلتقي القصة بالتنفيذ",
      quoteTitle: "ميزانيات متوقعة. نتائج متميزة.",
      quoteSteps: [
        { icon: "📝", title: "املأ النموذج", desc: "أخبرنا عن مشروعك وأهدافك" },
        { icon: "📞", title: "احصل على اتصال", desc: "يتواصل معك فريقنا خلال 24 ساعة" },
        { icon: "🎬", title: "أنجز مشروعك", desc: "تنفيذ منضبط من الفكرة إلى الإطار الأخير" },
      ],
      quotePillars: [
        "الإنتاج على أرض الواقع",
        "تطوير ملكية فكرية أصلية",
        "إنتاج إعلانات تجارية",
        "إنتاج أفلام وثائقية",
        "خدمات ما بعد الإنتاج",
      ],
      photographyBadge: "تصوير يتماشى مع الفيلم",
      photographyTitle: "Photography that matches the film.",
      photographyDesc: "صور الحملات، تغطية الفعاليات، البورتريه، وتصوير المنتجات والطعام بما يتماشى مع مخرجات الفيديو.",
      photographyTagline: "مصقول ومتناسق مع أسلوبك",
      photographyImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
      creativeTitle: "Creative Creations",
      creativeSubtitle: "Behind every Frame",
      blogBadge: "News & Insights",
      blogTitle: "News & Insights",
      blogSubtext: "Company news and updates",
      ctaBannerTitle: "لنحقق ذلك معاً. تواصل معنا الآن!",
      ctaBannerText: "تواصل معنا لمشروعك القادم — احصل على عرض سعر خلال 24 ساعة",
    },
    statsData: [
      { value: "3+", label: "مكاتب في المنطقة", icon: "🌍" },
      { value: "50+", label: "عميل راضٍ", icon: "🤝" },
      { value: "90%", label: "معدل العملاء المتكررين", icon: "⭐" },
      { value: "360°", label: "دورة إنتاج متكاملة", icon: "🎬" },
    ],
    servicesData: [
      { id: "photography", icon: "📷", title: "التصوير", shortDesc: "تصوير متميز للعلامات والمنتجات والتنفيذيين والفعاليات بإضاءة نظيفة وتسليم متسق.", price: "", fullDesc: "تصوير متميز للعلامات والمنتجات والتنفيذيين والفعاليات بإضاءة نظيفة وتسليم متسق.", features: [] },
      { id: "commercial", icon: "📺", title: "إنتاج الإعلانات التجارية", shortDesc: "إعلانات وأفلام حملات عالية التأثير من الفكرة إلى التصوير والتسليم النهائي.", price: "", fullDesc: "إعلانات وأفلام حملات عالية التأثير من الفكرة إلى التصوير والتسليم النهائي.", features: [] },
      { id: "post-production", icon: "✂️", title: "ما بعد الإنتاج والتسليم النهائي", shortDesc: "مونتاج، ألوان، صوت، mastering، ونسخ متعددة الصيغ تلبي مواصفات المنصات والبث.", price: "", fullDesc: "مونتاج، ألوان، صوت، mastering، ونسخ متعددة الصيغ تلبي مواصفات المنصات والبث.", features: [] },
      { id: "events", icon: "🎤", title: "تغطية الفعاليات والإنتاج المباشر", shortDesc: "تغطية متعددة الكامeras، بث مباشر، طائرات بدون طيار، ومontages في نفس اليوم للمؤتmerات والإطلاقات والحفلات.", price: "", fullDesc: "تغطية متعددة الكameras، بث مباشر، طائرات بدون طيار، ومontages في نفس اليوم للمؤتmerات والإطلاقات والحفلات.", features: [] },
      { id: "documentary", icon: "🎬", title: "إنتاج الأفلام الوثائقية", shortDesc: "أفلام وثائقية وسلاسل doc مبنية على البحث للمنصات والقنوات والمؤسسات.", price: "", fullDesc: "أفلام وثائقية وسلاسل doc مبنية على البحث للمنصات والقنوات والمؤسسات.", features: [] },
      { id: "on-ground-egypt", icon: "🇪🇬", title: "خدمات الإنتاج على أرض الواقع في مصر", shortDesc: "تصاريح، fixing، طاقم، معدات، لوجستيات، وlocation scouting للتصوير الدولي في مصر.", price: "", fullDesc: "تصاريح، fixing، طاقم، معدات، لوجستيات، وlocation scouting للتصوير الدولي في مصر.", features: [] },
      { id: "podcast", icon: "🎙️", title: "إنتاج البودكاست", shortDesc: "إنتاج بودكast صوتي ومرئي في الاستودio أو on location، مع montage ومقاطع للتوزيع.", price: "", fullDesc: "إنتاج بودكast صوتي ومرئي في الاستودio أو on location، مع montage ومقاطع للتوزيع.", features: [] },
      { id: "corporate", icon: "🏢", title: "المحتوى المؤسسي والصناعي", shortDesc: "أفلام مؤسسية واضحة وموثوقة للنفط والغاز والتعليم والعقارات والصناعات المعقدة.", price: "", fullDesc: "أفلام مؤسسية واضحة وموثوقة للنفط والغاز والتعليم والعقارات والصناعات المعقدة.", features: [] },
      { id: "tv-broadcast", icon: "📡", title: "إنتاج البرامج التلفزيونية والبث المباشر", shortDesc: "إنتاج استودio وميداني مع control room workflow وrun downs وحزم graphics وتسليم.", price: "", fullDesc: "إنتاج استودio وميداني مع control room workflow وrun downs وحزم graphics وتسليم.", features: [] },
      { id: "motion-cgi", icon: "✨", title: "الموشن CGI والمرئيات المدعومة بالذكاء الاصطناعي", shortDesc: "موشن 2D و3D وCGI ومرئيات بمساعدة AI لرفع السرد وشرح الأفكار المعقدة.", price: "", fullDesc: "موشن 2D و3D وCGI ومرئيات بمساعدة AI لرفع السرد وشرح الأفكار المعقدة.", features: [] },
      { id: "dubbing", icon: "🌐", title: "الدبلجة والتعليق الصوتي والتعريب", shortDesc: "ترجمة، تعليق صوتي، دبلجة، ADR، وتعبئة متعددة اللغات وفق معايير التسليم.", price: "", fullDesc: "ترجمة، تعليق صوتي، دبلجة، ADR، وتعبئة متعددة اللغات وفق معايير التسليم.", features: [] },
      { id: "marketing", icon: "📊", title: "حلول التسويق والأداء", shortDesc: "استراتيجية محتوى، media buying، اختبار إبداعي، وأنظمة حملات مبنية حول الإنتاج.", price: "", fullDesc: "استراتيجية محتوى، media buying، اختبار إبداعي، وأنظمة حملات مبنية حول الإنتاج.", features: [] },
    ],
    processData: {
      badge: "دورة الإنتاج",
      title: "The Untold Story تقدّم دورة الإنتاج الكاملة",
      steps: [
        { step: "١", title: "التخطيط", desc: "تطوير الفكرة، السيناريو، storyboard، والجدول الزمني." },
        { step: "٢", title: "التصوير", desc: "تصوير سينمائي احترافي في الاستوديو أو على location." },
        { step: "٣", title: "البث المباشر", desc: "تغطية حية للفعاليات والبث المباشر." },
        { step: "٤", title: "ما بعد الإنتاج", desc: "مونتاج، تصحيح ألوان، VFX، وتسليم نهائي." },
        { step: "٥", title: "التعريب", desc: "دبلجة وترجمة وتعريb لأسواق متعددة." },
      ]
    },
    testimonialsData: {
      badge: "Creative Creations",
      title: "Behind every Frame",
      list: [
        {
          name: "أحمد الشمري",
          role: "مدير تسويق، شركة النخبة",
          text: "Untold غيّرت طريقة تفكيرنا في التسويق الرقمي. النتائج تجاوزت توقعاتنا بكثير.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "سارة القحطاني",
          role: "رائدة أعمال",
          text: "تعاملت مع وكالات كثيرة لكن Untold الأكثر احترافية والأسرع في التنفيذ. أنصح بها بشدة.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "محمد العتيبي",
          role: "مؤسس، براند ماكس",
          text: "زادت مبيعاتنا ٣٠٠٪ خلال ٦ أشهر من العمل مع Untold. فريق رائع!",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "لطيفة الدوسري",
          role: "مديرة تنفيذية، ريادة",
          text: "الاحترافية والإبداع في كل تفصيلة. لن أتعامل مع أي وكالة أخرى بعد الآن.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
        },
      ]
    },
    faqData: {
      badge: "الأسئلة الشائعة",
      title: "أجوبة لأهم أسئلتك",
      list: [
        { q: "كم يستغرق تنفيذ الهوية البصرية؟", a: "عادةً ١٠–١٤ يوم عمل، تشمل مراحل البحث والتصميم والمراجعات." },
        { q: "هل تعملون مع الشركات الصغيرة؟", a: "نعم، لدينا باقات مناسبة لكل الأحجام من الفرد حتى الشركة الكبيرة." },
        { q: "كيف يتم الدفع؟", a: "نقبل الدفع بالتحويل البنكي أو المدى أو الفيزا. عادةً ٥٠٪ مقدم و٥٠٪ عند التسليم." },
        { q: "هل تقدمون تقارير للحملات؟", a: "بالطبع، تقارير أسبوعية وشهرية مفصّلة مع جميع المؤشرات الرئيسية." },
        { q: "هل يمكنني تعديل الباقة لاحقاً؟", a: "نعم، باقاتنا مرنة ويمكن تعديلها في أي وقت حسب احتياجاتك." },
      ]
    },
    aboutData: {
      badge: "من نحن",
      title: "حيث تولد الأفكار وتتشكّل القصص",
      subtext: "نقدّم دورة الإنتاج الكاملة للعلامات التجارية والمنصات والقنوات والمؤسسات التي تحتاج مرئيات متميزة بتنفيذ منضبط.",
      ceoName: "Khaled Bendary",
      ceoRole: "المدير التنفيذي",
      heroStats: [
        { value: "3+", label: "مكاتب في منطقة الشرق الأوسط وشمال أفريقيا" },
        { value: "50+", label: "عميل راضٍ" },
        { value: "90%", label: "معدل العملاء المتكررين" },
      ],
      storyBadge: "قصتنا",
      storyTitle: "The Untold Story استوديو إنتاج أفلام وفيديو متكامل الخدمات.",
      storyDesc1: "The Untold Story هو المكان الذي تولد فيه الأفكار وتتشكّل القصص. من الشرارة الأولى إلى الإطار الأخير، نصنع تجارب سينمائية تأسر وتُحرّك وتبقى في ذاكرة الجمهور.",
      storyDesc2: "نبتكر مرئيات جريئة لا تُنسى عبر الإعلانات التجارية والأفلام الوثائقية وأفلام العلامات التجارية والفعاليات الحية والبودكاست والتصوير والموشن/CGI، بإتقان ولمسة مميزة. إنتاج متعدد اللغات؟ نغطيه أيضاً.",
      storyDesc3: "للإنتاجات الدولية في مصر، نتولى كل شيء على أرض الواقع — من التصاريح والطاقم واللوجستيات والمواقع إلى الدعم الإنتاجي الكامل — حتى تتجسّد رؤيتك بسلاسة.",
      storyDesc4: "وراء مشاريع العملاء، نطوّر قصصاً وصيغاً أصلية مصمّمة للسفر والإلهام والبقاء مع الجمهور طويلاً بعد أن يخفت الشاشة.",
      storyCta: "تواصل معنا",
      storyImage: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop",
      aboutStats: [
        { value: "3+", label: "مكاتب في منطقة الشرق الأوسط وشمال أفريقيا", icon: "🌍" },
        { value: "50+", label: "عميل راضٍ", icon: "🤝" },
        { value: "90%", label: "معدل العملاء المتكررين", icon: "⭐" },
        { value: "360°", label: "دورة إنتاج متكاملة", icon: "🎬" },
      ],
      missionTitle: "مهمتنا",
      missionDesc: "تقديم دورة الإنتاج الكاملة للعلامات التجارية والمنصات والقنوات والمؤسسات التي تحتاج مرئيات متميزة بتنفيذ منضبط.",
      visionTitle: "رؤيتنا",
      visionDesc: "صناعة تجارب سينمائية تأسر وتُحرّك وتبقى مع الجمهور — من الشرارة الأولى إلى الإطار الأخير.",
      valuesBadge: "ما الذي نقدمه",
      valuesTitle: "إنتاج شامل بإتقان",
      valuesList: [
        { icon: "🎬", title: "دورة إنتاج متكاملة", desc: "من الفكرة إلى الإطار النهائي، نتولى كل مرحلة بدقة ولمسة مميزة." },
        { icon: "🌐", title: "إنتاج متعدد اللغات", desc: "إنتاج جاهز للعالم عبر اللغات والأسواق — نغطيه بالكامل." },
        { icon: "🇪🇬", title: "مركز الإنتاج في مصر", desc: "تصاريح وطاقم ولوجستيات ومواقع ودعم كامل على أرض الواقع للتصوير الدولي." },
        { icon: "✨", title: "سرد أصلي", desc: "نطوّر قصصاً وصيغاً مصمّمة للسفر والإلهام والبقاء." },
      ],
      teamBadge: "القيادة",
      teamTitle: "قيادة The Untold Story",
      teamList: [
        { name: "Khaled Bendary", role: "المدير التنفيذي", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop", bio: "يقود The Untold Story برؤية لإنتاج مرئي متميز بتنفيذ منضبط عبر منطقة الشرق الأوسط وشمال أفريقيا." },
      ],
      partnersBadge: "موثوق من قبل عمالقة الصناعة",
      partnersTitle: "Trusted By Industry Titans",
    },
    servicesPage: {
      badge: "خدماتنا",
      title: "خدماتنا",
      subtext: "استوديو إنتاج أفلام وفيديو متكامل في مصر ومنطقة الشرق الأوسط وشمال أفريقيا. اختر خدمة أدناه أو أرسل brief وسنوصي بالإعداد المناسب.",
      gridBadge: "خدماتنا",
      gridTitle: "اختر خدمة أدناه",
      quoteTitle: "احصل على عرض سعر",
      quoteSubtext: "أرسل brief وسنرد بالخطة المناسبة والخطوات التالية.",
      quoteEmailLabel: "البريد الإلكتروني",
      quoteEmail: "bendary@globaluntoldstory.com",
      quotePhoneLabel: "الهاتف وWhatsApp",
      quotePhone: "+20 100 129 9639",
      quoteForm: {
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        interestedIn: "مهتم بـ",
        message: "رسالة عن الخدمة",
        chooseService: "اختر خدمة",
        submit: "احصل على عرض سعر",
      },
      whyTitle: "لماذا The Untold Story?",
      whyList: [
        { icon: "🎬", title: "دورة إنتاج متكاملة", desc: "من التخطيط والتصوير إلى ما بعد الإنتاج والتعريب والتسليم النهائي." },
        { icon: "🌍", title: "المنطقة والعالم", desc: "مكاتب في مصر ودبي وجدة لخدمة العملاء حول العالم." },
        { icon: "🇪🇬", title: "إنتاج على أرض الواقع في مصر", desc: "تصاريح وطاقم ومعدات ولوجستيات ومواقع للتصوير الدولي." },
        { icon: "⚡", title: "تنفيذ منضبط", desc: "ميزانيات متوقعة، نتائج متميزة، وخطوات واضحة." },
      ],
      ctaTitle: "احصل على عرض سعر",
      ctaSub: "أرسل brief وسنرد بالخطة المناسبة والخطوات التالية.",
      ctaBtn: "احصل على عرض سعر",
    },
    contactPage: {
      badge: "تواصل معنا",
      title: "نحن هنا لمساعدتك",
      subtext: "أرسل لنا رسالة وسيتواصل معك أحد خبرائنا في أقرب وقت ممكن",
      infoTitle: "معلومات الاتصال",
      email: "bendary@globaluntoldstory.com",
      offices: [
        {
          title: "مكتب مصر",
          flag: "🇪🇬",
          city: "مصر",
          country: "مصر",
          address: "مدينة الإنتاج الإعلامي، مصر",
          phone: "+201001299639",
          email: "bendary@globaluntoldstory.com",
          time: "GMT+2",
          status: "المقر الرئيسي",
        },
        {
          title: "مكتب الإمارات",
          flag: "🇦🇪",
          city: "دبي",
          country: "الإمارات العربية المتحدة",
          address: "Business Bay, Dubai, UAE",
          phone: "+971547711772",
          time: "GMT+4",
          status: "مكتب إقليمي",
        },
        {
          title: "مكتب السعودية",
          flag: "🇸🇦",
          city: "جدة",
          country: "المملكة العربية السعودية",
          address: "جدة، المملكة العربية السعودية",
          phone: "+201001299639",
          time: "GMT+3",
          status: "مكتب إقليمي",
        },
      ],
      officesSectionTitle: "مكاتبنا",
      officesSectionSubtext: "نحن موجودون في مصر والإمارات وجدة لنكون دائماً قريبين منك",
      formTitle: "أرسل رسالة",
      labels: {
        name: "الاسم الكامل *",
        email: "البريد الإلكتروني *",
        phone: "رقم الهاتف",
        service: "الخدمة المطلوبة",
        message: "رسالتك *",
        chooseService: "اختر الخدمة",
      },
      placeholders: {
        name: "أحمد محمد",
        email: "ahmed@example.com",
        phone: "+20 10 01299639",
        message: "أخبرنا عن مشروعك وما تحتاجه...",
      }
    },
    blogPage: {
      badge: "المدونة",
      title: "آخر الأخبار والرؤى التسويقية",
      subtext: "تابع أحدث المقالات والإلهامات حول الإعلان الرقمي، التسويق، والهوية البصرية.",
      posts: [
        {
          id: "post-1",
          title: "كيف ترفع عائد الاستثمار من حملاتك الرقمية",
          excerpt: "أسرار اختيار الجمهور الصحيح، صياغة الرسالة الأمثل، وتحليل الأرقام لتحسين الأداء.",
          date: "٢٠ يونيو ٢٠٢٦",
          category: "إعلان رقمي",
        },
        {
          id: "post-2",
          title: "أهم ٥ اتجاهات في تصميم الهوية البصرية لعام ٢٠٢٦",
          excerpt: "اكتشف ملامح التصميم التي تساعد علامتك التجارية على البروز في السوق.",
          date: "١٥ يونيو ٢٠٢٦",
          category: "تصميم",
        },
        {
          id: "post-3",
          title: "طرق مبتكرة لبناء استراتيجية محتوى فعّالة",
          excerpt: "من الفكرة إلى التوزيع — كيف تصنع محتوى يجذب العملاء ويحتفظ بهم.",
          date: "١٠ يونيو ٢٠٢٦",
          category: "محتوى",
        }
      ]
    },
    footer: {
      brandDesc: "The Untold Story — استوديو إنتاج أفلام وفيديو متكامل في مصر ومنطقة الشرق الأوسط وشمال أفريقيا.",
      aboutTitle: "عن الشركة",
      aboutLinks: [
        { href: "/about", label: "من نحن" },
        { href: "/portfolio", label: "أعمالنا" },
        { href: "/contact", label: "تواصل معنا" },
      ],
      servicesTitle: "صفحات أخرى",
      serviceLinks: [
        { href: "/services/documentary", label: "إنتاج أفلام وثائقية" },
        { href: "/services/original-ip", label: "تطوير ملكية فكرية أصلية" },
        { href: "/services/podcast", label: "إنتاج بودكاست" },
        { href: "/services/photography", label: "التصوير" },
      ],
      quickLinks: "روابط سريعة",
      contactUs: "تواصل معنا",
      emailLabel: "البريد الإلكتروني",
      allRights: "جميع الحقوق محفوظة.",
      adminDashboard: "لوحة تحكم الإدارة ←",
      offices: [
        { region: "مصر", address: "مدينة الإنتاج الإعلامي", phone: "+201001299639" },
        { region: "الإمارات", address: "UAE – Dubai – Business Bay", phone: "+971547711772" },
        { region: "السعودية - جدة", address: "جدة، المملكة العربية السعودية", phone: "+201001299639" },
      ],
    },
    announcementBar: "احصل على عرض سعر خلال 24 ساعة — تواصل معنا لمشروعك القادم",
    showAnnouncementBar: true
  },
  en: {
    siteConfig: {
      name: "The Untold Story",
      tagline: "Film & Video Production Studio",
      description: "Film & video production services in Egypt and MENA. The Untold Story delivers the full production cycle.",
      email: "bendary@globaluntoldstory.com",
      phone: "+201001299639",
      address: "Egyptian Media Production City, Egypt",
      workingHours: "Sunday – Thursday, 9AM – 6PM",
      socialLinks: {
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        linkedin: "https://linkedin.com",
        youtube: "https://youtube.com",
      },
    },
    navLinks: [
      { href: "/", label: "Home" },
      { href: "/about", label: "About Us" },
      { href: "/services", label: "Services" },
      { href: "/portfolio", label: "Portfolio" },
      { href: "/blog", label: "Blogs" },
      { href: "/contact", label: "Contact" },
    ],
    common: {
      dashboardBtn: "Dashboard",
      readMore: "Read More",
      requestService: "Get a Quote",
      contactUs: "Contact Us",
      contactUsNow: "Get in Touch Now",
      exploreServices: "Our Services",
      allServices: "More services for your needs. Get in touch",
      successTitle: "Sent Successfully!",
      successDesc: "We have received your message and our team will get in touch within 24 hours.",
      sendAnother: "Send Another Message",
      loading: "⏳ Sending...",
      submitBtn: "Send Message",
      whyUs: "Why The Untold Story?",
    },
    heroData: {
      badge: "🎬 Film & Video Production services in Egypt and MENA",
      headline1: "The Untold Story delivers",
      headline2: "the full production cycle",
      subtext: "Film, video, advertising, documentaries, corporate content, TV shows, and more. With offices in Egypt Media Production City, Dubai, and Jeddah serving MENA and clients worldwide.",
      cta1: { label: "Contact us for Next project →", href: "/contact" },
      cta2: { label: "Our Work", href: "/portfolio" },
      image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop",
      imageAlt: "Professional film and video production",
      badges: ["Planning ✓", "Filming ✓", "Post Production ✓", "Localization ✓"],
      quoteBadge: "Get a quote in 24h",
    },
    homeData: {
      servicesBadge: "Our Storytelling & Production Expertise",
      servicesTitle: "Our Storytelling & Production Expertise",
      servicesSubtext: "End-to-end production for brands, platforms, broadcasters, and institutions",
      servicesCta: "More services for your needs. Get in touch",
      productionPipeline: ["Planning", "Filming", "Live", "Post & final delivery", "Localization"],
      portfolioTitle: "Projects done by The Untold Story",
      quoteBadge: "Where story meets execution",
      quoteTitle: "Predictable budgets. Premium results.",
      quoteSteps: [
        { icon: "📝", title: "Fill out the form", desc: "Tell us about your project and goals" },
        { icon: "📞", title: "Get a call back", desc: "Our team reaches out within 24 hours" },
        { icon: "🎬", title: "Get your project done", desc: "Disciplined execution from spark to final frame" },
      ],
      quotePillars: [
        "On-Ground Production",
        "Original IP Development",
        "Commercial Advertising Production",
        "Documentary Production",
        "Post Production Services",
      ],
      photographyBadge: "Photography",
      photographyTitle: "Photography that matches the film.",
      photographyDesc: "Campaign stills, event coverage, portraits, and product and food photography shot to align with your video deliverables.",
      photographyTagline: "Polished and aligned with your tone",
      photographyImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
      creativeTitle: "Creative Creations",
      creativeSubtitle: "Behind every Frame",
      blogBadge: "News & Insights",
      blogTitle: "News & Insights",
      blogSubtext: "Company news and updates",
      ctaBannerTitle: "Let's make it happen. Get in touch now!",
      ctaBannerText: "Contact us for your next project — get a quote in 24h",
    },
    statsData: [
      { value: "3+", label: "Offices across MENA", icon: "🌍" },
      { value: "50+", label: "Satisfied clients", icon: "🤝" },
      { value: "90%", label: "Repeat business rate", icon: "⭐" },
      { value: "360°", label: "Full production cycle", icon: "🎬" },
    ],
    servicesData: [
      { id: "photography", icon: "📷", title: "Photography", shortDesc: "Premium photography for brands, products, executives, and events with clean lighting and consistent delivery.", price: "", fullDesc: "Premium photography for brands, products, executives, and events with clean lighting and consistent delivery.", features: [] },
      { id: "commercial", icon: "📺", title: "Commercial Advertising Production", shortDesc: "High impact commercials and campaign films from concept to filming and final delivery.", price: "", fullDesc: "High impact commercials and campaign films from concept to filming and final delivery.", features: [] },
      { id: "post-production", icon: "✂️", title: "Post Production and Final Delivery", shortDesc: "Editing, color, sound, mastering, and multi format versions that meet platform and broadcast specs.", price: "", fullDesc: "Editing, color, sound, mastering, and multi format versions that meet platform and broadcast specs.", features: [] },
      { id: "events", icon: "🎤", title: "Event Coverage and Live Production", shortDesc: "Multi camera coverage, live streaming, drone, and same day edits for conferences, launches, and concerts.", price: "", fullDesc: "Multi camera coverage, live streaming, drone, and same day edits for conferences, launches, and concerts.", features: [] },
      { id: "documentary", icon: "🎬", title: "Documentary Production", shortDesc: "Research led documentaries and doc series built for platforms, broadcasters, and institutions.", price: "", fullDesc: "Research led documentaries and doc series built for platforms, broadcasters, and institutions.", features: [] },
      { id: "on-ground-egypt", icon: "🇪🇬", title: "On Ground Production Services in Egypt", shortDesc: "Permits, fixing, crew, gear, logistics, and location scouting for international shoots across Egypt.", price: "", fullDesc: "Permits, fixing, crew, gear, logistics, and location scouting for international shoots across Egypt.", features: [] },
      { id: "podcast", icon: "🎙️", title: "Podcast Production", shortDesc: "Audio and video podcast production with studio or on location setup, editing, and clips for distribution.", price: "", fullDesc: "Audio and video podcast production with studio or on location setup, editing, and clips for distribution.", features: [] },
      { id: "corporate", icon: "🏢", title: "Corporate and Industrial Content", shortDesc: "Clear, credible corporate films for oil and gas, education, real estate, and complex industries.", price: "", fullDesc: "Clear, credible corporate films for oil and gas, education, real estate, and complex industries.", features: [] },
      { id: "tv-broadcast", icon: "📡", title: "TV Shows and Live Broadcast Production", shortDesc: "Studio and field production with control room workflow, run downs, graphics packages, and delivery.", price: "", fullDesc: "Studio and field production with control room workflow, run downs, graphics packages, and delivery.", features: [] },
      { id: "motion-cgi", icon: "✨", title: "Motion CGI and AI Powered Visuals", shortDesc: "2D motion, 3D, CGI, and AI assisted visuals to elevate storytelling and explain complex ideas.", price: "", fullDesc: "2D motion, 3D, CGI, and AI assisted visuals to elevate storytelling and explain complex ideas.", features: [] },
      { id: "dubbing", icon: "🌐", title: "Dubbing Voice Over and Localization", shortDesc: "Subtitles, voice over, dubbing, ADR, and multi language packaging aligned with delivery standards.", price: "", fullDesc: "Subtitles, voice over, dubbing, ADR, and multi language packaging aligned with delivery standards.", features: [] },
      { id: "marketing", icon: "📊", title: "Marketing Solutions and Performance", shortDesc: "Content strategy, media buying, creative testing, and campaign systems built around production.", price: "", fullDesc: "Content strategy, media buying, creative testing, and campaign systems built around production.", features: [] },
    ],
    processData: {
      badge: "Production Cycle",
      title: "The Untold Story delivers the full production cycle",
      steps: [
        { step: "1", title: "Planning", desc: "Concept development, scripting, storyboards, and scheduling." },
        { step: "2", title: "Filming", desc: "Professional cinematic filming in studio or on location." },
        { step: "3", title: "Live", desc: "Live event coverage and real-time production support." },
        { step: "4", title: "Post & final delivery", desc: "Editing, color grading, VFX, and final delivery." },
        { step: "5", title: "Localization", desc: "Dubbing, translation, and localization for multiple markets." },
      ]
    },
    testimonialsData: {
      badge: "Creative Creations",
      title: "Behind every Frame",
      list: [
        {
          name: "Commercial Production",
          role: "Bold visuals for brands",
          text: "From concept to final frame — commercials that captivate, move, and stay with audiences.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "Documentary Production",
          role: "Stories that travel",
          text: "Real stories crafted with cinematic precision and disciplined execution.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "Post Production",
          role: "Premium finishing",
          text: "Editing, color, VFX, and sound — polished and aligned with your tone.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1574717026530-2e874b7698a8?q=80&w=150&auto=format&fit=crop",
        },
        {
          name: "On-Ground Production",
          role: "Egypt & MENA",
          text: "Permits, crews, logistics, locations, and full on-the-ground support for international shoots.",
          rating: 5,
          avatar: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=150&auto=format&fit=crop",
        },
      ]
    },
    faqData: {
      badge: "FAQ",
      title: "Answers to Your Key Questions",
      list: [
        { q: "How long does a brand identity take?", a: "Typically 10-14 business days, including research, design drafts, and revisions." },
        { q: "Do you work with small businesses?", a: "Yes, we have tailored packages designed for setups of all sizes, from startups to corporates." },
        { q: "What are the payment terms?", a: "We accept bank transfers and major cards. Terms are usually 50% upfront and 50% upon delivery." },
        { q: "Do you provide campaign reports?", a: "Absolutely. We supply detailed weekly and monthly reports tracking all major key performance indicators (KPIs)." },
        { q: "Can I upgrade or downgrade my plan later?", a: "Yes, our plans are flexible and can be adapted at any time according to your business needs." },
      ]
    },
    aboutData: {
      badge: "About Us",
      title: "Where Ideas Come Alive and Stories Take Shape",
      subtext: "We deliver the complete production cycle for brands, platforms, broadcasters, and institutions that need premium visuals with disciplined execution.",
      ceoName: "Khaled Bendary",
      ceoRole: "CEO",
      heroStats: [
        { value: "3+", label: "Offices across the MENA region" },
        { value: "50+", label: "Satisfied clients" },
        { value: "90%", label: "Repeat business rate" },
      ],
      storyBadge: "Our Story",
      storyTitle: "The Untold Story is a full-service film and video production studio.",
      storyDesc1: "The Untold Story is where ideas come alive and stories take shape. From the first spark to the final frame, we craft cinematic experiences that captivate, move, and stay with audiences.",
      storyDesc2: "We create bold, unforgettable visuals across commercials, documentaries, branded films, live events, podcasts, photography, and motion/CGI, delivered with precision and flair. Multilingual production? We have that covered, too.",
      storyDesc3: "For international productions in Egypt, we handle everything on the ground, from permits, crews, logistics, and locations to full production support, so your vision unfolds seamlessly.",
      storyDesc4: "Beyond client projects, we develop original stories and formats designed to travel, inspire, and stay with audiences long after the screen fades.",
      storyCta: "Get in Touch",
      storyImage: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop",
      aboutStats: [
        { value: "3+", label: "Offices across MENA", icon: "🌍" },
        { value: "50+", label: "Satisfied clients", icon: "🤝" },
        { value: "90%", label: "Repeat business rate", icon: "⭐" },
        { value: "360°", label: "Full production cycle", icon: "🎬" },
      ],
      missionTitle: "Our Mission",
      missionDesc: "We deliver the complete production cycle for brands, platforms, broadcasters, and institutions that need premium visuals with disciplined execution.",
      visionTitle: "Our Vision",
      visionDesc: "To craft cinematic experiences that captivate, move, and stay with audiences — from the first spark to the final frame.",
      valuesBadge: "What We Offer",
      valuesTitle: "End-to-End Production Excellence",
      valuesList: [
        { icon: "🎬", title: "Full Production Cycle", desc: "From concept to final frame, we handle every stage with precision and flair." },
        { icon: "🌐", title: "Multilingual Production", desc: "Global-ready production across languages and markets — we've got you covered." },
        { icon: "🇪🇬", title: "Egypt Production Hub", desc: "Permits, crews, logistics, locations, and full on-the-ground support for international shoots." },
        { icon: "✨", title: "Original Storytelling", desc: "Beyond client work, we develop formats designed to travel, inspire, and endure." },
      ],
      teamBadge: "Leadership",
      teamTitle: "Leading The Untold Story",
      teamList: [
        { name: "Khaled Bendary", role: "CEO", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop", bio: "Leading The Untold Story with a vision for premium visual production and disciplined execution across the MENA region." },
      ],
      partnersBadge: "Trusted By Industry Titans",
      partnersTitle: "Trusted By Industry Titans",
    },
    servicesPage: {
      badge: "Services",
      title: "Services",
      subtext: "A full service film and video production studio across Egypt and MENA. Choose a service below or send your brief and we will recommend the right setup.",
      gridBadge: "Our Services",
      gridTitle: "Choose a service below",
      quoteTitle: "Get a Quote",
      quoteSubtext: "Send your brief and we will respond with the right plan and next steps.",
      quoteEmailLabel: "Email",
      quoteEmail: "bendary@globaluntoldstory.com",
      quotePhoneLabel: "Phone and WhatsApp",
      quotePhone: "+20 100 129 9639",
      quoteForm: {
        fullName: "Full name",
        email: "Email address",
        phone: "Phone number",
        interestedIn: "Interested in",
        message: "Message about service",
        chooseService: "Select a service",
        submit: "Get a Quote",
      },
      whyTitle: "Why The Untold Story?",
      whyList: [
        { icon: "🎬", title: "Full Production Cycle", desc: "From planning and filming to post, localization, and final delivery." },
        { icon: "🌍", title: "MENA & Global Reach", desc: "Offices in Egypt, Dubai, and Jeddah serving clients worldwide." },
        { icon: "🇪🇬", title: "On-Ground in Egypt", desc: "Permits, crews, gear, logistics, and locations for international shoots." },
        { icon: "⚡", title: "Disciplined Execution", desc: "Predictable budgets, premium results, and clear next steps." },
      ],
      ctaTitle: "Get a Quote",
      ctaSub: "Send your brief and we will respond with the right plan and next steps.",
      ctaBtn: "Get a Quote",
    },
    contactPage: {
      badge: "Contact Us",
      title: "We Are Here to Help",
      subtext: "Send us a message and one of our experts will get in touch shortly.",
      infoTitle: "Contact Info",
      email: "bendary@globaluntoldstory.com",
      offices: [
        {
          title: "Egypt Office",
          flag: "🇪🇬",
          city: "Egypt",
          country: "Egypt",
          address: "Egyptian Media Production City, Egypt",
          phone: "+201001299639",
          email: "bendary@globaluntoldstory.com",
          time: "GMT+2",
          status: "Main Office",
        },
        {
          title: "UAE Office",
          flag: "🇦🇪",
          city: "Dubai",
          country: "UAE",
          address: "Business Bay, Dubai, UAE",
          phone: "+971547711772",
          time: "GMT+4",
          status: "Regional Office",
        },
        {
          title: "KSA Office",
          flag: "🇸🇦",
          city: "Jeddah",
          country: "KSA",
          address: "Jeddah, Saudi Arabia",
          phone: "+201001299639",
          time: "GMT+3",
          status: "Regional Office",
        },
      ],
      officesSectionTitle: "Our Offices",
      officesSectionSubtext: "We are present in Egypt, the UAE, and Jeddah to always be close to you",
      formTitle: "Send a Message",
      labels: {
        name: "Full Name *",
        email: "Email Address *",
        phone: "Phone Number",
        service: "Requested Service",
        message: "Your Message *",
        chooseService: "Choose a Service",
      },
      placeholders: {
        name: "John Doe",
        email: "john@example.com",
        phone: "+20 10 01299639",
        message: "Tell us about your project requirements and goals...",
      }
    },
    blogPage: {
      badge: "News & Insights",
      title: "News & Insights",
      subtext: "Company news and updates",
      posts: [
        {
          id: "post-1",
          title: "How to Boost ROI from Your Digital Campaigns",
          excerpt: "Discover the secrets of audience targeting, message crafting, and analytics optimization.",
          date: "June 20, 2026",
          category: "Digital Ads",
        },
        {
          id: "post-2",
          title: "Top 5 Brand Identity Trends for 2026",
          excerpt: "Learn the design cues that will help your brand stand out in a competitive market.",
          date: "June 15, 2026",
          category: "Design",
        },
        {
          id: "post-3",
          title: "Creative Content Strategy Techniques That Work",
          excerpt: "From idea to distribution — how to build content that attracts and retains customers.",
          date: "June 10, 2026",
          category: "Content",
        }
      ]
    },
    footer: {
      brandDesc: "The Untold Story a full-service film and video production studio in Egypt and MENA.",
      aboutTitle: "About",
      aboutLinks: [
        { href: "/about", label: "About us" },
        { href: "/portfolio", label: "Our Portfolio" },
        { href: "/contact", label: "Get in touch" },
      ],
      servicesTitle: "Other pages",
      serviceLinks: [
        { href: "/services/documentary", label: "Documentary Production" },
        { href: "/services/original-ip", label: "Original IP Development" },
        { href: "/services/podcast", label: "Podcast Production" },
        { href: "/services/photography", label: "Photography" },
      ],
      quickLinks: "Quick Links",
      contactUs: "Contact Us",
      emailLabel: "Email address",
      allRights: "All rights reserved.",
      adminDashboard: "Admin Dashboard →",
      offices: [
        { region: "Egypt", address: "Egyptian Media Production City", phone: "+201001299639" },
        { region: "UAE", address: "UAE – Dubai – Business Bay", phone: "+971547711772" },
        { region: "KSA Jeddah", address: "Jeddah, Saudi Arabia", phone: "+201001299639" },
      ],
    },
    announcementBar: "Get a quote in 24h — Contact us for your next project",
    showAnnouncementBar: true
  }
};

translations.ar.servicesData = withServiceImages(translations.ar.servicesData);
translations.en.servicesData = withServiceImages(translations.en.servicesData);

export type StaticLocale = keyof typeof translations;

export function getStaticTranslation(locale: Locale): Translation {
  if (locale in translations) {
    return translations[locale as StaticLocale];
  }
  return translations[FALLBACK_LOCALE as StaticLocale];
}
export type ServiceDataItem = Omit<
  (typeof translations.ar.servicesData)[number],
  "features"
> & {
  features: string[];
  imageUrl?: string;
};
export type Translation = Omit<typeof translations.ar, "servicesData"> & {
  servicesData: ServiceDataItem[];
};
export type StatDataItem = typeof translations.ar.statsData[number];
export type ProcessStep = typeof translations.ar.processData.steps[number];
export type TestimonialItem = typeof translations.ar.testimonialsData.list[number];
export type WhyListItem = typeof translations.ar.servicesPage.whyList[number];
export type InfoItem = typeof translations.ar.contactPage.offices[number];
export type FaqItem = typeof translations.ar.faqData.list[number];
export type TeamMember = typeof translations.ar.aboutData.teamList[number];
export type ValueItem = typeof translations.ar.aboutData.valuesList[number];

